Repository barrage-studios/SeasonShift, pull requests merged in 2019-11, with the labels that each got.

#82 Feature/global powerup
  Game/Assets/Global/Visuals/Concept_Powerup_Bomb.png
  Game/Assets/Global/Visuals/Pixel_Powerup_Bomb.png
  Game/Assets/Global/Visuals/Placeholder.png
  Game/Assets/Global/Visuals/Placeholder.png.meta
Labels: Team: Art

#84 Feature/summer pixel art
  Game/Assets/Summer/Visuals/Pixel_Background_Island.png
  Game/Assets/Summer/Visuals/Pixel_Background_Ocean.png
  Game/Assets/Summer/Visuals/Pixel_Boss_Sun.png
  Game/Assets/Summer/Visuals/Pixel_Bullet_Coral.png
  Game/Assets/Summer/Visuals/Pixel_Bullet_Fireball.png
  Game/Assets/Summer/Visuals/Pixel_Bullet_Laser.png
  Game/Assets/Summer/Visuals/Pixel_Bullet_Pearl.png
  Game/Assets/Summer/Visuals/Pixel_Bullet_Sand.png
  Game/Assets/Summer/Visuals/Pixel_Bullet_Seashell.png
  Game/Assets/Summer/Visuals/Pixel_Bullet_Shocker.png
  Game/Assets/Summer/Visuals/Pixel_Spawner_JellyfishPink.png
  Game/Assets/Summer/Visuals/Pixel_Spawner_SandDollar.png
  Game/Assets/Summer/Visuals/Pixel_Spawner_Seashell.png
  Game/Assets/Summer/Visuals/Pixel_Spawner_Starfish.png
  Game/Assets/Summer/Visuals/Pixel_SummerBoss (4).png
  Game/Assets/Summer/Visuals/Pixel_SummerEnemy (2).png
Labels: Team: Art

#85 Feature/spring pixel art
  Game/Assets/Editor.meta
  Game/Assets/Editor/WebGLBuilder.cs.meta
  Game/Assets/Spring/Visuals/Pixel_Boss_Hive.png
  Game/Assets/Spring/Visuals/Pixel_Bullet_CosmosPetal.png
  Game/Assets/Spring/Visuals/Pixel_Bullet_Honeycomb.png
  Game/Assets/Spring/Visuals/Pixel_Bullet_MorningGloryPetal.png
  Game/Assets/Spring/Visuals/Pixel_Bullet_Pansie.png
  Game/Assets/Spring/Visuals/Pixel_Bullet_Seed.png
  Game/Assets/Spring/Visuals/Pixel_Bullet_Stinger.png
  Game/Assets/Spring/Visuals/Pixel_Bullet_Strawberry.png
  Game/Assets/Spring/Visuals/Pixel_Enemy_Bee.png
  Game/Assets/Spring/Visuals/Pixel_OrangeFlower.png
  Game/Assets/Spring/Visuals/Pixel_RedFlower.png
  Game/Assets/Spring/Visuals/Pixel_Spawner_Cosmos.png
  Game/Assets/Spring/Visuals/Pixel_Spawner_MorningGlory.png
  Game/Assets/Spring/Visuals/Pixel_Spawner_Pansie.png
  Game/Assets/Spring/Visuals/Pixel_SpringBoss.png
  Game/Assets/Spring/Visuals/Pixel_SpringEnemy.png
  Game/Assets/Spring/Visuals/Placeholder.png
  Game/Assets/Spring/Visuals/Placeholder.png.meta
Labels: Team: Art

#87 Feature/spring sfx
  Game/Assets/Spring/Audio/Spring_SFX_01_Bee.wav
  Game/Assets/Spring/Audio/Spring_SFX_02_FlowerBurst.wav
Labels: Team: Art, Type: Enhancement

#92 Feature/fall pixel art
  Game/Assets/Fall/Pixel_Background_Fall.png
  Game/Assets/Fall/Pixel_Background_FallBoss.png
  Game/Assets/Fall/Visuals/Pixel_Boss_Pumpkin.png
  Game/Assets/Fall/Visuals/Pixel_Bullet_Candy.png
  Game/Assets/Fall/Visuals/Pixel_Bullet_CandyCorn.png
  Game/Assets/Fall/Visuals/Pixel_Bullet_Fang.png
  Game/Assets/Fall/Visuals/Pixel_Bullet_Leaf.png
  Game/Assets/Fall/Visuals/Pixel_Bullet_Lolipop.png
  Game/Assets/Fall/Visuals/Pixel_Bullet_Spider.png
  Game/Assets/Fall/Visuals/Pixel_Bullet_SpiderEgg.png
  Game/Assets/Fall/Visuals/Pixel_Spawner_Acorn.png
  Game/Assets/Fall/Visuals/Pixel_Spawner_Bat.png
  Game/Assets/Fall/Visuals/Pixel_Spawner_Leaf.png
  Game/Assets/Fall/Visuals/Pixel_Spawner_Spiderweb.png
Labels: Team: Art

#93 Feature/winter pixel art
  Game/Assets/Winter/Visuals/Pixel_Background_Boss (3).png
  Game/Assets/Winter/Visuals/Pixel_Boss_Snowman.png
  Game/Assets/Winter/Visuals/Pixel_Bullet_Carrot.png
  Game/Assets/Winter/Visuals/Pixel_Bullet_Coal.png
  Game/Assets/Winter/Visuals/Pixel_Bullet_Gumdrop.png
  Game/Assets/Winter/Visuals/Pixel_Bullet_Iceshard.png
  Game/Assets/Winter/Visuals/Pixel_Bullet_Icicle.png
  Game/Assets/Winter/Visuals/Pixel_Bullet_SmallSnowball.png
  Game/Assets/Winter/Visuals/Pixel_Bullet_Snowball.png
  Game/Assets/Winter/Visuals/Pixel_Bullet_YarnBall.png
  Game/Assets/Winter/Visuals/Pixel_Enemy_Snowman.png
  Game/Assets/Winter/Visuals/Pixel_Spawner_GingerbreadMan.png
  Game/Assets/Winter/Visuals/Pixel_Spawner_Scarf.png
  Game/Assets/Winter/Visuals/Pixel_Spawner_Snowflake.png
  Game/Assets/Winter/Visuals/pixel_winterbg (2).png
Labels: Team: Art

#100 Feature/global character
  Game/Assets/Global/Visuals/Pixel_Character_Back.png
  Game/Assets/Global/Visuals/Pixel_Character_Front.png
  Game/Assets/Global/Visuals/charactersketch.png
Labels: Team: Art, Type: Enhancement

#97 Feature/ui art
  Game/Assets/Global/UI/fallUI.png
  Game/Assets/Global/UI/fallsketch.png
  Game/Assets/Global/UI/springUI.png
  Game/Assets/Global/UI/springsketch.png
  Game/Assets/Global/UI/summerUI.png
  Game/Assets/Global/UI/summersketch.png
  Game/Assets/Global/UI/winterUI.png
  Game/Assets/Global/UI/wintersketch.png
Labels: Team: Art

#101 Feature/storyboard
  Game/Assets/Story/Pixel_Death_MeltedSnowman.png
  Game/Assets/Winter/Visuals/Pixel_Death_MeltedSnowman.png
Labels: Team: Art, Type: Enhancement

#102 Feature/global sfx
  Game/Assets/Global/Audio/Global_SFX_01_Cursor.wav
  Game/Assets/Global/Audio/Global_SFX_02_SelectButton.wav
  Game/Assets/Global/Audio/Global_SFX_03_BackButton.wav
  Game/Assets/Global/Audio/Global_SFX_04_BossDeath.wav
  Game/Assets/Global/Audio/Global_SFX_05_Pew.wav
  Game/Assets/Global/Audio/Global_SFX_06_Explosion.wav
Labels: Team: Sound, Type: Enhancement
