Repository barrage-studios/SeasonShift, pull requests merged in 2019-12, with the labels that each got.

#104 Feature/summer sfx
  Game/Assets/Global/Audio/Summer_SFX_Burning.wav
  Game/Assets/Global/Audio/Summer_SFX_Burning2.wav
  Game/Assets/Summer/Audio/Summer_SFX_01_Zap.wav
  Game/Assets/Summer/Audio/Summer_SFX_02_Waves.wav
Labels: Team: Sound, Type: Enhancement

#106 Feature/spring sfx
  SpringAssets/Audio/Spring_SFX_01_Bee.wav
  SpringAssets/Audio/Spring_SFX_02_FlowerBurst.wav
Labels: Team: Sound, Type: Enhancement

#110 Feature/winter sfx
  Game/Assets/Winter/Audio/Winter_BGM_1.wav
  Game/Assets/Winter/Audio/Winter_SFX_01_Freezing.wav
Labels: Priority: Critical, Team: Sound, Type: Enhancement

#115 Remove Non-members
  .github/README.md
Labels: Priority: Low, Team: Global, Type: Documentation
